GET http://localhost:3000/songs



###Get contact by id
GET http://localhost:3000/songs/6917a2fccb095a5ad4ee70e2




###CREATE CONTACT
POST http://localhost:3000/songs
content-type: application/json

{
    "NameSong": "32 minutos",   
    "Author": "ALGO",
    "duration": "3:51",
    "releaseDate": "Desconocido",
    "genre": "POP",
    "language": "Spanish",
    "album": "Desconocido"
  }



### PUT CONTACT/ UPDATE/ Actualizar un array
PUT http://localhost:3000/songs/6917a7f6f4f1449 HTTP/1.1
content-type: application/json

{
    "NameSong": "Yano es el valiente",
    "Author": "Actualizacion",
    "duration": "3:51",
    "releaseDate": "Desconocido",
    "genre": "Desconocido",
    "language": "Spanish",
    "album": "Desconocido"
  }



### DELETE Contact
DELETE http://localhost:3000/songs/6917d7ae8adf493d8f6c776a